### ISSUE TITLE
Money collection system

### ISSUE THREAD

**Issue by RonAsis** [RonAsis/Wsep202#10]
Calling an external system by transferring transaction information to this system and obtaining confirmation that the collection was successful. Required to enable change / replacement of the external system without impairing system activity

1. create sequence diagram.
2. create a Main success scenario.
3. create a Main failure scenario.

 * for complex case you need to split it.
 * If there are use case that are the very similar you don't need to write it again ,only represent the differences.

**Comment by RonAsis** [comment]
add headers to the pages  : h1 , h2 , h3

**Comment by KseniaDr** [comment]
done

**Comment by RonAsis** [comment]
Please add the link to the home page

**Comment by KseniaDr** [comment]
done
