### ISSUE TITLE
domains' tests & trading system's tests

### ISSUE THREAD

**Issue by noyasi** [RonAsis/Wsep202#108]

**Comment by KseniaDr** [comment]
fixed unit test in TradingSystemTest: https://github.com/RonAsis/Wsep202/pull/126/commits/44feaa0a1a83adb0ba391051c460f98f4a289da7

**Comment by KseniaDr** [comment]
integration purchase method: https://github.com/RonAsis/Wsep202/pull/145/commits/17aae55b273583a5970adbb190a002d6639cef9d
