### ISSUE TITLE
Add option to remove owner from store

### ISSUE THREAD

**Issue by RonAsis** [RonAsis/Wsep202#171]

**Comment by KseniaDr** [comment]
method was added: https://github.com/RonAsis/Wsep202/commit/3cc2cd8da4566e9c57ffd87acf5bddd5acf9728e

**Comment by KseniaDr** [comment]
done: https://github.com/RonAsis/Wsep202/commit/8a95fcac7f430ef76e875b901dd5e020ca07aef0
