### ISSUE TITLE
Constraints Correctness

### ISSUE THREAD

**Issue by KseniaDr** [RonAsis/Wsep202#20]
1. change according to the new class diagram.
2. every 'test' needs to be more abstract.
3. add constraint number 5.
4. in constrains number 3 take b instead of a.

**Comment by MoranNeptune** [comment]
Add links to the main titles.

**Comment by KseniaDr** [comment]
fixed, please check and approve it.

**Comment by KseniaDr** [comment]
https://github.com/RonAsis/Wsep202/wiki/Constraints-Correctness-Version-1
