### ISSUE TITLE
Testing testing and more testing.... (unit & integration in the domain)

### ISSUE THREAD

**Issue by barPerlman** [RonAsis/Wsep202#215]
distribute for responsibilities:

1.initialFiles(new) - Bar
2.TradingSystemFacade(27) - Bar
3.discount package(80) - Bar
4.External service management(24) - Bar

1.policy_purchase package(new) - Ksenia
2.TradingSystem(90) - Ksenia

1.Store(96) - Moran
2.MangerStore(16) - Moran

1.notification package -Noy
2.Product(6) - Noy
3.ShoppingBag(27) - Noy
4.ShoppingCart(37) - Noy
5.UserSystem(22) - Noy

**Comment by KseniaDr** [comment]
trading: https://github.com/RonAsis/Wsep202/pull/268/commits/afa52e17fcb3001841069982900fe5f6403a61ce
