### ISSUE TITLE
make sure that TradingSystemDaoImpl implements ALL of the functions in TradingSystemDao

### ISSUE THREAD

**Issue by noyasi** [RonAsis/Wsep202#229]
add the following fucntion to TradingSystemDaoImpl:  
@Override
    public void updateStoreAndUserSystem(Store ownedStore, UserSystem userSystem) {
        stores.add(ownedStore);
        users.add(userSystem);
    }

there are other functions to add

**Comment by RonAsis** [comment]
All the functions exists all the other in the default interface not need for memory only for Db
