### ISSUE TITLE
change getShoppingCart in TradingSystemDaoImpl

### ISSUE THREAD

**Issue by noyasi** [RonAsis/Wsep202#231]
you need to check if the given user is in administrators and not only if it's in users

 @Override
    public ShoppingCart getShoppingCart(String username, UUID uuid) {
        if(isValidUuid(username, uuid)){
            if (users.stream().anyMatch(userSystem -> userSystem.getUserName().equals(username)))
                return users.stream()
                        .filter(userSystem -> userSystem.getUserName().equals(username))
                        .findFirst()
                        .map(UserSystem::getShoppingCart)
                        .orElseThrow(()-> new UserDontExistInTheSystemException(username));
            else
                return administrators.stream()
                        .filter(userSystem -> userSystem.getUserName().equals(username))
                        .findFirst()
                        .map(UserSystem::getShoppingCart)
                        .orElseThrow(()-> new UserDontExistInTheSystemException(username));
        }
        throw new UserDontExistInTheSystemException(username);
    }

**Comment by MoranNeptune** [comment]
fix this.
