### ISSUE TITLE
change cloneProduct() in product

### ISSUE THREAD

**Issue by noyasi** [RonAsis/Wsep202#235]
you need to clone ALL of the product's data :

   public Product cloneProduct(){
        Product returnedProduct =  new Product(name,category,amount,cost,storeId);
        returnedProduct.setProductSn(productSn);
        returnedProduct.setOriginalCost(originalCost);
        returnedProduct.setRank(rank);
        return returnedProduct;
    }

**Comment by MoranNeptune** [comment]
fix this.
