### ISSUE TITLE
change addProduct(..) in TradingSystemFacade 

### ISSUE THREAD

**Issue by noyasi** [RonAsis/Wsep202#236]
return Objects.nonNull(productRes) ? modelMapper.map(**productRes**, ProductDto.class)  
AND NOT:
 return Objects.nonNull(productRes) ? modelMapper.map(**product**, ProductDto.class) 

public ProductDto addProduct(@NotBlank String ownerUsername, int storeId,
                                 @NotBlank String productName, @NotBlank String category,
                                 int amount, double cost, UUID uuid) {
        try {
            UserSystem user = tradingSystem.getUser(ownerUsername, uuid); //get registered user with ownerUsername
            Store ownerStore = user.getOwnerOrManagerWithPermission(storeId, StorePermission.EDIT_PRODUCT); //verify he owns store with storeId
            //convert to a category we can add to the product
            ProductCategory productCategory = ProductCategory.getProductCategory(category);
            Product product = factoryObjects.createProduct(productName, productCategory, amount, cost, storeId);
            Product productRes = tradingSystemDao.addProductToStore(ownerStore, user, product);
            return Objects.nonNull(productRes) ? modelMapper.map(**productRes**, ProductDto.class) : null;
        } catch (TradingSystemException e) {
            log.error("add product failed", e);
            return null;
        }
    }

**Comment by MoranNeptune** [comment]
fix this
