### ISSUE TITLE
fixing use case 1.1, 5.1, 6.4

### ISSUE THREAD

**Issue by MoranNeptune** [RonAsis/Wsep202#24]
1. abstract sequence (without inside methods).
2. actions more abstract (home page is not good).
3. everyone who uses the system is an actor.
4. sequence needs to be abstract and describe the api only (without inside methods).

**Comment by noyasi** [comment]
The tradingSystem is not an actor, please remove it.

**Comment by noyasi** [comment]
Was done along time ago.. ;)
