### ISSUE TITLE
fix addProduct(...) in TradingSystemFacade

### ISSUE THREAD

**Issue by noyasi** [RonAsis/Wsep202#241]
I added a check to make sure that amount and cost aren't negative:

 public ProductDto addProduct(@NotBlank String ownerUsername, int storeId,
                                 @NotBlank String productName, @NotBlank String category,
                                 int amount, double cost, UUID uuid) {
        try {
            if (cost<0 || amount<0) {
                log.error("cost and amount can't be negative");
                return null;
            }
            UserSystem user = tradingSystem.getUser(ownerUsername, uuid); //get registered user with ownerUsername
            Store ownerStore = user.getOwnerOrManagerWithPermission(storeId, StorePermission.EDIT_PRODUCT); //verify he owns store with storeId
            //convert to a category we can add to the product
            ProductCategory productCategory = ProductCategory.getProductCategory(category);
            Product product = factoryObjects.createProduct(productName, productCategory, amount, cost, storeId);
            Product productRes = tradingSystemDao.addProductToStore(ownerStore, user, product);
            return Objects.nonNull(productRes) ? modelMapper.map(productRes, ProductDto.class) : null;
        } catch (TradingSystemException e) {
            log.error("add product failed", e);
            return null;
        }
    }

**Comment by MoranNeptune** [comment]
fixed
