### ISSUE TITLE
Store +StorePermmision + storeManager + ExternalServiceManagement

### ISSUE THREAD

**Issue by MoranNeptune** [RonAsis/Wsep202#25]
- Add logger
- Add relevant DTO's
- Complete the code.
- Perform unite testing and integration testing
- Check code coverage

**Comment by barPerlman** [comment]
security system added in pull request: [https://github.com/RonAsis/Wsep202/pull/43](url)

**Comment by barPerlman** [comment]
[https://github.com/RonAsis/Wsep202/pull/43](url)

**Comment by barPerlman** [comment]
[https://github.com/RonAsis/Wsep202/pull/44](url)
