### ISSUE TITLE
fix addProductToCart(...) in ShoppingCart

### ISSUE THREAD

**Issue by noyasi** [RonAsis/Wsep202#254]
I added a line to check if the product is null before calling log

    public boolean addProductToCart(Store storeOfProduct, Product productToAdd, int amountOfProduct){
        boolean response = false;
        if(checkParameters(storeOfProduct,productToAdd) && isProductInStore(storeOfProduct, productToAdd)) {
            if(shoppingBagsList.keySet().stream()
                    .noneMatch(store -> store.getStoreId() == storeOfProduct.getStoreId())){
                ShoppingBag storeShoppingBag = new ShoppingBag(storeOfProduct);
                response =  storeShoppingBag.addProductToBag(productToAdd, amountOfProduct) && addBagToCart(storeOfProduct, storeShoppingBag);
            }else{
                Store storeInShoppingBag = shoppingBagsList.keySet().stream()
                        .filter(store -> store.getStoreId() == storeOfProduct.getStoreId())
                        .findFirst().get();
                shoppingBagsList.get(storeInShoppingBag).addProductToBag(productToAdd,amountOfProduct);
                response  = true;
            }
        }
        if (productToAdd!=null)
            log.info(String.format("the product %s  %s to cart", productToAdd.getName(), response? "added" : "not added"));
        else
            log.info("the null product not added to cart");

        return response;
    }

**Comment by MoranNeptune** [comment]
fix this.
