### ISSUE TITLE
PurchasePolicy + PurchaseType + DiscountType + DiscountPolicy + ShoppingBag + ShoppingCart +UserSystem

### ISSUE THREAD

**Issue by MoranNeptune** [RonAsis/Wsep202#26]
- Add logger
- Add relevant DTO's
- Complete the code.
- Perform unite testing and integration testing
- Check code coverage
- check code coverage

**Comment by KseniaDr** [comment]
ShoppingBag: https://github.com/RonAsis/Wsep202/pull/46
ShoppingCart: https://github.com/RonAsis/Wsep202/pull/47
UserSystem: https://github.com/RonAsis/Wsep202/pull/51

**Comment by KseniaDr** [comment]
last version
https://github.com/RonAsis/Wsep202/pull/69
https://github.com/RonAsis/Wsep202/pull/79
