### ISSUE TITLE
init productListFromStore in ShoppingBag

### ISSUE THREAD

**Issue by noyasi** [RonAsis/Wsep202#274]
when calling the noArgsConstructor productListFromStore  is null,
the solution:

    @ElementCollection(fetch = FetchType.EAGER)
    @Cascade(value = org.hibernate.annotations.CascadeType.ALL)
    @MapKeyColumn(name = "products")
    private Map<Product, Integer> productListFromStore = new HashMap<>();

**Comment by MoranNeptune** [comment]
fix this.
