### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by barPerlman** [RonAsis/Wsep202#3]
White class diagram which defines the relations and hierarchy between classes that covers the requirements.

**Comment by KseniaDr** [comment]
A guest holds 1...* ShoppingBag, which represent the shopping cart. Each ShopingBag is connected to 1 store (the diamond needs to be removed, instead there should be a two-way arrow). Each strore is connected to 0...* ShoppingBag.
![1](https://user-images.githubusercontent.com/37842196/76871322-934c4b80-6873-11ea-9973-c41e9235cecb.jpeg)

**Comment by MoranNeptune** [comment]
there are 2 equal entities: SellerStoreManager and StpreManager.

**Comment by noyasi** [comment]
![36104018-19a5-4559-9b42-c9edcbac0076](https://user-images.githubusercontent.com/37842801/76909706-a6cbd680-68b4-11ea-8c38-faa72827ba3c.jpeg)

**Comment by noyasi** [comment]
a connection between the receipt, the user and the store needs to be added.

**Comment by barPerlman** [comment]
![image](https://user-images.githubusercontent.com/37221013/76941331-8166b900-6904-11ea-82e3-322507daae30.png)

**Comment by barPerlman** [comment]
I think there should be a relation of 1 to many between the management classes to their DAO classes, since there are many systems,users,receipts, etc. in the system.
as suggested in above png file.
