### ISSUE TITLE
TradingSystemFunctions : buyShoppingCart, openStore, registerNewUser, login, loginAdministrator, isRegisteredAdministrator, purchaseShoppingCart, purchaseShoppingCart

### ISSUE THREAD

**Issue by MoranNeptune** [RonAsis/Wsep202#31]
code:
- write the code for those functions.
- write unit and integration tests for those functions.
- add comments.
- use logger.

**Comment by KseniaDr** [comment]
did openStore, merged login & loginAdministrator,  deleted isRegisteredAdministrator, and did registerNewUser for now

**Comment by KseniaDr** [comment]
https://github.com/RonAsis/Wsep202/pull/42

**Comment by KseniaDr** [comment]
payment + billing for purchase : https://github.com/RonAsis/Wsep202/pull/58
purchase: https://github.com/RonAsis/Wsep202/pull/63
