### ISSUE TITLE
TradingSystemFunctions: loginRegularUser, isRegisteredUser, closeStore, getUserOpt, logout, getAdministratorUser, getAdministratorUserOpt, isAdmin

### ISSUE THREAD

**Issue by MoranNeptune** [RonAsis/Wsep202#32]
code:

- write the code for those functions.
- write unit and integration tests for those functions.
- add comments.
- use logger.

**Comment by barPerlman** [comment]
related pull request: [](https://github.com/RonAsis/Wsep202/pull/38)

**Comment by barPerlman** [comment]
close store functionality removed due to irrelevant to this version (v1)
