### ISSUE TITLE
Buyer-Guest 2.2,2.3,2.4,2.5,2.6,2.7,2.8

### ISSUE THREAD

**Issue by RonAsis** [RonAsis/Wsep202#5]
2.2. A guest can register for the system by entering identifying information and setting a password. At the end of a successful guest registration process, the system is registered as a subscriber. It still has to make an identified login.
2.3. User is subscribed.
2.4 Viewing Information about Stores and Products in Stores.
2.5. Searching for a product without focusing on a specific store, by product name, category or keywords. The results can also be filtered based on characteristics such as price range, product rating, category, store rating, etc. 
2.6. Saving products at a shopping cart for any store for purchase at some point during the current visit to the system.
2.7. Viewing and Editing a Shopping Cart. Purchase of products according to the types of purchase and possible discount types for guests, according to the store's purchase and discount policy, and their availability in full.
2.8.Purchase of products according to the types of purchase and possible discount types for guests, according to the store's purchase and discount policy, and their availability in full.

For each the above:
1. create sequence diagram.
2. create a Main success scenario.
3. create a Main failure scenario.

* for complex case you need to split it.
* If there are use case that are the very similar you don't need to write it again ,only represent the differences.

**Comment by RonAsis** [comment]
Please organize all the Text There . There are a lot '/ '.

**Comment by RonAsis** [comment]
In Addition all the sequence Diagram put in the match Use Case

**Comment by barPerlman** [comment]
a new updated and fixed document is uploaded for your review.

**Comment by barPerlman** [comment]
done

‫בתאריך יום ו׳, 20 במרץ 2020 ב-8:58 מאת ‪RonAsis‬‏ <‪
notifications@github.com‬‏>:‬
