### ISSUE TITLE
Buyer Subscription : 3.1, 3.2,3.7

### ISSUE THREAD

**Issue by RonAsis** [RonAsis/Wsep202#6]
3.1 Logout from the system.
3.2.Subscription of system can open shop.
3.7.Viewing Personal Purchase History.

For each the above:
   1. create sequence diagram.
   2. create a Main success scenario.
   3. create a Main failure scenario.

 * for complex case you need to split it.
 * If there are use case that are the very similar you don't need to write it again ,only represent the differences.

**Comment by RonAsis** [comment]
add headers to the pages  : h1 , h2 , h3

**Comment by KseniaDr** [comment]
done
