### ISSUE TITLE
Fixing AT tables

### ISSUE THREAD

**Issue by MoranNeptune** [RonAsis/Wsep202#82]
fixing acceptance tests in all use-cases - **to VERSION2**

**Comment by KseniaDr** [comment]
Fixed mine.
uc 3.1:https://github.com/RonAsis/Wsep202/wiki/UC-3.1-Acceptance-Tests-Logout-from-the-system
uc 3.2:https://github.com/RonAsis/Wsep202/wiki/UC-3.2-Acceptance-Tests-Open-a-store
uc 3.7:https://github.com/RonAsis/Wsep202/wiki/UC-3.7-Acceptance-Tests-View-personal-purchase-history

**Comment by barPerlman** [comment]
Fixed my acceptance tests:
[uc 2.2](https://github.com/RonAsis/Wsep202/wiki/UC-2.2-Acceptance-Tests---Guest-registration)
[uc 2.3](https://github.com/RonAsis/Wsep202/wiki/UC-2.3-Acceptance-Tests-Guest-login)
[uc 2.4.1](https://github.com/RonAsis/Wsep202/wiki/UC-2.4.1-Acceptance-Tests-Guest-watch-on-store-information)
[uc 2.4.2](https://github.com/RonAsis/Wsep202/wiki/UC-2.4.2-Acceptance-Tests-Guest-watch-on-products-in-store-information)
[uc 2.5.1.1](https://github.com/RonAsis/Wsep202/wiki/UC-2.5.1.1:-Guest-search-products-by-name-acceptance-tests)
[uc 2.5.1.2](https://github.com/RonAsis/Wsep202/wiki/UC-2.5.1.2:-Guest-search-products-by-category-acceptance-tests)
[uc 2.5.1.3](https://github.com/RonAsis/Wsep202/wiki/UC-2.5.1.3:-Guest-search-product-by-keyword-acceptance-tests)
[uc 2.5.2.1](https://github.com/RonAsis/Wsep202/wiki/UC-2.5.2.1-Acceptance-Tests-Guest-filter-by-price-range-acceptance-test)
[uc 2.5.2.2](https://github.com/RonAsis/Wsep202/wiki/UC-2.5.2.2-Acceptance-Tests-Guest-filter-by-product-rank-acceptance-test)
[uc 2.5.2.3](https://github.com/RonAsis/Wsep202/wiki/UC-2.5.2.3:-Guest-filter-by-category-acceptance-tests)
[uc 2.5.2.4](https://github.com/RonAsis/Wsep202/wiki/UC-2.5.2.4:-Guest-filter-by-store-rank-acceptance-tests)
[uc 2.6](https://github.com/RonAsis/Wsep202/wiki/UC-2.6:-Guest-save-in-shopping-bag-acceptance-tests)
[uc 2.7.1](https://github.com/RonAsis/Wsep202/wiki/UC-2.7.1:-Guest-watch-on-his-shopping-cart-acceptance-tests)
[uc 2.7.2](https://github.com/RonAsis/Wsep202/wiki/UC-2.7.2:-Guest-edit-shopping-cart-acceptance-tests)
[uc 2.8.1.1](https://github.com/RonAsis/Wsep202/wiki/UC-2.8.1.1:-Immediate-purchase-acceptance-tests)
[uc 2.8.2.1](https://github.com/RonAsis/Wsep202/wiki/UC-2.8.2.1:-Visible-discount-acceptance-tests)
