### ISSUE TITLE
test with shopping cart - empty

### ISSUE THREAD

**Issue by RonAsis** [RonAsis/Wsep202#95]

**Comment by KseniaDr** [comment]
added fixed unit test to purchase shoppingCart in TradingSystemTest: https://github.com/RonAsis/Wsep202/pull/126/commits/44feaa0a1a83adb0ba391051c460f98f4a289da7

**Comment by KseniaDr** [comment]
integration purchased method: https://github.com/RonAsis/Wsep202/pull/145/commits/17aae55b273583a5970adbb190a002d6639cef9d
