### ISSUE TITLE
add test for check owner and manger that added to them

### ISSUE THREAD

**Issue by RonAsis** [RonAsis/Wsep202#99]
need to check when added owner / manger he added one in the the store and one the in the user.

**Comment by KseniaDr** [comment]
added more test unit test from this methods: https://github.com/RonAsis/Wsep202/pull/126/commits/44feaa0a1a83adb0ba391051c460f98f4a289da7

**Comment by KseniaDr** [comment]
https://github.com/RonAsis/Wsep202/pull/146/commits/7deedd5fadc24505f2ecf9bc1df3c336283b7aa7
